#SET
# set1={1,2,True,"hi",45,"hello",100,4.4}
# print(len(set1))
# set1.add(6)
# print(set1)
# set1.remove(100)
# print(set1)
# set1.pop()
# print(set1)
# set1.update({8,7})
# print(set1)
# set2={"good","sun","moon",250}
# print(set2.union(set1))
# set3={2,"moon"}
# print(set3.intersection(set2))
# #remove duplicates from list using set
# list1=[1,1,2,3,5,6,6]
# set1=set(list1)
# print(set1)


#input set and sum of elements
# n=int(input("enter the elements"))
# set1=set()
# sum=0
# for i in range(1,n+1):
#     num=int(input("enter the elemnts"))
#     set1.add(num) 
#     sum=sum+i    
# print(set1)
# print("sum of elements :",sum)    


#
list1=[1,22,32,44,5,6]
list2=[2,4,44,6,33,90,10]